#define Identificador 1
#define Constante_Entera 1
#define Cadena 3
#define Operador_Modulo 4
#define Operador_Not_Equal 5
#define Operador_Negacion 6
#define Operador_Modulo_Asignacion 7
#define Operador_Asignacion 8
#define Comentario 9
#define Comilla 10
#define Parentesis_Izq 11
#define Parentesis_Der 12
#define Llave_Izq 13
#define Llave_Der 14
#define Corchete_Izq 15
#define Corchete_Der 16
#define Coma 17
#define Punto_Coma 18
#define int 19
#define boolean 20
#define string 21
#define return 22
#define for 23
#define input 24
#define print 25
#define function 26
#define if 27